name: Deploy to WordPress.org
variables:
  workingDirectory: './addons-for-pixel'
on:
  push:
    branches:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build # Remove or modify this step as needed
        run: |
          cd 
          npm install
          npm run build
          working-directory: "$(workingDirectory)"
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: addons-for-pixel
