name: Deploy to WordPress.org

on:
  push:
    branches:
      - "*"

defaults:
  run:
    working-directory: addons-for-pixel

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build # Remove or modify this step as needed
        run: |
          cd /home/runner/work/addons-for-pixel
          npm install
          npm run build
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: addons-for-pixel
